version: '3.7'

services:
  php:
    build: docker/php
    command: ["/wait-for-it.sh", "keycloak:8080"]
    depends_on:
      - keycloak
    volumes:
    - .:/app:rw
    working_dir: /app

  keycloak:
    image: jboss/keycloak:13.0.0
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - '8080:8080'