version: '3.7'

services:
  php-cli:
    build:
      context: .
      dockerfile: docker/php-cli/Dockerfile
    container_name: php
    image: php:7.4-cli
    volumes:
    - .:/var/www/code:rw

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
