version: '3.7'

services:
  php:
    image: php:8.0-cli
    volumes:
    - .:/app:rw
    working_dir: /app

  keycloak:
    image: jboss/keycloak:13.0.0
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - '8080:8080'
