on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: PHP Unit

jobs:
  Unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite unit

      #- name: Generate code coverage report
      #  uses: irongut/CodeCoverageSummary@v1.3.0
      #  with:
      #    filename: phpunit.cobertura.xml
      #    badge: true
      #    output: both
