on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: PHP Analysis

jobs:
  Analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phpstan
        run: vendor/bin/phpstan analyze src tests

      - name: Run psalm
        run: vendor/bin/psalm src

      - name: Run ecs
        run: vendor/bin/ecs check src tests
