on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: PHP Integration (Keycloak compatibility)

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        keycloak: [ 17.0.0, 18.0.0 ]

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v3
        with:
          build-args: >
            KEYCLOAK_VERSION: ${{ matrix.keycloak }}
          file: docker/keycloak/Dockerfile
          outputs: type=docker,dest=/tmp/${{ github.sha }}-${{ matrix.keycloak }}.tar
          tags: ${{ github.repository }}:${{ github.sha }}-${{ matrix.keycloak }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-${{ matrix.keycloak }}
          path: /tmp/${{ github.sha }}-${{ matrix.keycloak }}.tar

  Integration:
    runs-on: ubuntu-latest

    needs: Build

    strategy:
      matrix:
        keycloak: [17.0.0, 18.0.0]

    env:
      KEYCLOAK_BASE_URL: 'http://localhost:8080'

    services:
      keycloak:
        image: /tmp/${{ github.sha }}-${{ matrix.keycloak }}.tar
        env:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
          - '8080:8080'

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Wait for Keycloak
        uses: iFaxity/wait-on-action@v1
        with:
          resource: ${{ env.KEYCLOAK_BASE_URL }}

      - name: Run integration tests
        run: vendor/bin/phpunit --testsuite integration
