on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: PHP Integration (Keycloak compatibility)

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        keycloak: [ 17.0.0-legacy, 18.0.0-legacy ]

    steps:
      - uses: actions/checkout@v2

      - run: |
          docker build -t ghcr.io/fschmtt/keycloak:${{ matrix.keycloak }} --build-arg KEYCLOAK_VERSION=${{ matrix.keycloak }} docker/keycloak
          docker login ghcr.io ${{ secrets.GITHUB_TOKEN }}
          docker push ghcr.io/fschmtt/keycloak:${{ matrix.keycloak }}
          docker logout ghcr.io

  Integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        keycloak: [17.0.0, 18.0.0]

    env:
      KEYCLOAK_BASE_URL: 'http://localhost:8080'

    services:
      keycloak:
        image: ghcr.io/fschmtt/keycloak:${{ matrix.keycloak }}
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
        ports:
          - '8080:8080'

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Wait for Keycloak
        uses: iFaxity/wait-on-action@v1
        with:
          resource: ${{ env.KEYCLOAK_BASE_URL }}

      - name: Run integration tests
        run: vendor/bin/phpunit --testsuite integration
