on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite unit

      - name: Run integration tests
        run: |
          docker-compose -f docker-compose.github.yml up -d php
          docker-compose -f docker-compose.github.yml run --rm php vendor/bin/phpunit --testsuite integration
          docker-compose -f docker-compose.github.yml down