on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    #container: php:8.0-cli
    #strategy:
    #  matrix:
    #    keycloak-version:
    #      - 13.0.0
    #      - 14.0.0
    #      - 15.0.0

    env:
      KEYCLOAK_BASE_URL: 'http://localhost:8080'

    services:
      keycloak:
        image: jboss/keycloak:13.0.0
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
        ports:
          - '8080:8080'

    steps:
      - uses: actions/checkout@v2

      - name: Identify PHP version
        run: php -v

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phpstan
        run: vendor/bin/phpstan analyze src tests

      - name: Run psalm
        run: vendor/bin/psalm src

      - name: Run code sniffer
        run: vendor/bin/phpcs --standard=PSR12 src tests

      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite unit

      - name: Wait for Keycloak...
        uses: iFaxity/wait-on-action@v1
        with:
          resource: http://localhost:8080

      - name: Run integration tests
        run: vendor/bin/phpunit --testsuite integration
